### ISSUE TITLE
Bitmap print function cutting off top half of images

### ISSUE THREAD

**Issue by proffalken** [luopio/py-thermal-printer#10]
Hi,

I'm generating qrcodes to be used with the thermal printer using the qrcode library (https://pypi.python.org/pypi/qrcode).  The codes generate fine (I can see them on the file system and scan them from my phone) however when I try and print them using the barcode call, the first couple of rows of the image get chopped off giving me an invalid barcode.

The code is as follows:

```
#!/usr/bin/env python
import printer
import qrcode
from qrcode.image.pure import PymagingImage

p = printer.ThermalPrinter(serialport="/dev/ttyAMA0")
qr = qrcode.QRCode(
      version=None,
      error_correction=qrcode.constants.ERROR_CORRECT_M
      )

qr.add_data('TEST')
qr.make(fit=True)

im = qr.make_image()
w, h = im.size
data = list(im.getdata())
p.linefeed()
p.linefeed()
p.print_text("TEST")
p.linefeed()
p.linefeed()
p.print_bitmap(data,w,h,True)
p.linefeed()
p.linefeed()
p.linefeed()
p.linefeed()

```

If anyone can shed light on why I'm missing some of the QRcode that would be great!

Cheers,

Matt

P.S. FWIW, Text prints fine :)

**Comment by luopio** [comment]
I take it that by saying that the codes generate fine you mean also that the "print-output.png" file (that is outputted by print_bitmap by giving the last parameter as True) looks like the real thing?

If so then I'm guessing some issue with too much data flowing into the printer. I've run into similar issues with larger images. Maybe you can try to print the QR-code in two or three slices? Each slice waiting for the previous to be printed with a simple sleep()-call or similar.

**Comment by proffalken** [comment]
Yeah, that's exactly what I mean.

OK, I'll give that a go, thanks :)
