### ISSUE TITLE
cut paper

### ISSUE THREAD

**Issue by alduxvm** [luopio/py-thermal-printer#11]
I believe this printer is capable of cutting paper, but the function is not implemented... have you ever try that?

**Comment by luopio** [comment]
I think the ones I've slightly dismantled didn't have any machine controllable cutting mechanism. Just a sharp edge to cut the paper.

**Comment by alduxvm** [comment]
Indeed, I read all the manual and search a lot, and apparently no cutting blade, sorry for this. cheers!
