### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by b4rtt** [luopio/py-thermal-printer#15]
hey, it's possible to set different encoding? My printer is printing chinese chars by default.

thanks

**Comment by luopio** [comment]
Hi, sorry for the delay. I think it's definitely possible. IIRC we don't have that method implemented, but creating that should be straightforward. It seems that this library has it, so porting to Python is all that is left https://github.com/adafruit/Adafruit-Thermal-Printer-Library/blob/master/Adafruit_Thermal.h

Would love a PR on this!

**Comment by b4rtt** [comment]
Thanks for your response. I tried it but with no success. Do you think that it could be caused because I have RS232 printer instead of TTL? I will buy RS232 to TTL converter and try to connect it. If it works I will prepare PR.

Thanks! :+1: :)

**Comment by luopio** [comment]
Dunno if that might be the issue. Hope the converter solves it. Good luck!
